# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4dfa109f919ef5c718cea9be1c3ef67"
name = "ce-pre-purchase"
handle = "ce-pre-purchase"
application_url = "https://brandon-achievements-burke-evaluate.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://brandon-achievements-burke-evaluate.trycloudflare.com/auth/callback",
  "https://brandon-achievements-burke-evaluate.trycloudflare.com/auth/shopify/callback",
  "https://brandon-achievements-burke-evaluate.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
